export const types = {
    ADD_TO_CART: "[Shop] ADD_TO_CART",
    REMOVE_FROM_CART: "[Shop] REMOVE_FROM_CART",
    ADJUST_QUANTITY: "[Shop] ADJUST_QUANTITY",
    LOAD_CURRENT_ITEM: "[Shop] LOAD_CURRENT_ITEM",
    EMPTY_CART: '[Shop] EMPTY_CART',
    // START_DOWNLOADING_PRODUCTS: '[Shop] START_DOWNLOADING_PRODUCTS',
    // PRODUCT_DOWNLOAD_SUCCESSFULL: '[Shop] PRODUCT_DOWNLOAD_SUCCESSFULL',
    // PRODUCT_DOWNLOAD_ERROR: '[Shop] PRODUCT_DOWNLOAD_ERROR'
}